require "matano.options"
require "matano.plugins"
require "matano.colorscheme"
require "matano.nvimtree"
require "matano.keymaps"
require "matano.telescope"
require "matano.treesitter"
require "matano.autopairs"
require "matano.cmp"
require "matano.lsp"
require "matano.lualine"
require "matano.comment"
require "matano.gitsigns"
require "matano.trouble"

